# Generated by Django 3.0.8 on 2020-07-30 19:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('Web Development', 'Web Development'), ('App Development', 'App Development'), ('Politics', 'Politics'), ('Mental Health', 'Mental Health'), ('Travel', 'Travel'), ('Social Issues', 'Social Issues'), ('College Experience', 'College Experience'), ('Photography', 'Photography'), ('Wildlife', 'Wildlife'), ('Natural Disaster Management', 'Natural Disaster Management'), ('Lifestyle', 'Lifestyle'), ('Fitness And Workout', 'Fitness And Workout'), ('Competitive Programming', 'Competitive Programming'), ('Astrology', 'Astrology'), ('Science And Research', 'Science And Research'), ('Others', 'Others')], default='Others', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(default=datetime.datetime(2020, 7, 30, 19, 5, 52, 637631, tzinfo=utc))),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(default=datetime.datetime(2020, 7, 30, 19, 5, 52, 638628, tzinfo=utc))),
                ('approved_comment', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Blogpost')),
            ],
        ),
    ]
