# Generated by Django 3.0.8 on 2020-07-30 19:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 30, 19, 12, 20, 982602, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 30, 19, 12, 20, 982602, tzinfo=utc)),
        ),
    ]
