# Generated by Django 3.0.8 on 2020-08-01 03:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200801_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 3, 18, 30, 69401, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 3, 18, 30, 69401, tzinfo=utc)),
        ),
    ]
